[build-system]
requires = [
    "setuptools >= 40.0.4",
    "wheel >= 0.29.0",
]
build-backend = 'setuptools.build_meta'

[project]
name = "tox-example-plugin"
version = "0.1"

[project.entry-points.tox]
example-plugin = "tox_example_plugin"
